import fs from "fs/promises";
import path from "path";
import matter from "gray-matter";
import { serialize } from "next-mdx-remote/serialize";
import rehypeKatex from "rehype-katex";
import remarkGfm from "remark-gfm";
import remarkMath from "remark-math";
import type { StrictFunction, TrustContext } from "katex";
import { Post, PostMetaData, MathTooltipDefinition } from "@/types/posts";
import { remarkMathTooltips } from "@/lib/remark/remark-math-tooltips";
import { rehypeMathTooltips } from "@/lib/rehype/rehype-math-tooltips";
import { coerceStage, coerceConfidence, deriveExcerpt } from "@/lib/content/schema";
import { labelForCategory } from "@/lib/content/categories";
import type { GraphEdge } from "@/lib/content/link-graph";

const katexTrust = (context: TrustContext) => context.command === "\\htmlClass";
const katexStrict: StrictFunction = (code) =>
  code === "htmlExtension" ? "ignore" : "warn";

const POSTS_DIR = path.join(process.cwd(), "content/posts");
const CONTENT_META = path.join(process.cwd(), "lib/generated/content-meta.json");

interface ContentMetaEntry {
  tended: string;
  outgoing: GraphEdge[];
  backlinks: string[];
}
interface ContentMeta {
  posts: Record<string, ContentMetaEntry>;
}

// Generated by scripts/generate-content-meta.ts at build time. Read once and
// memoized; falls back gracefully (updated = logged date, no backlinks) if absent.
let contentMetaCache: ContentMeta | null | undefined;
async function loadContentMeta(): Promise<ContentMeta | null> {
  if (contentMetaCache !== undefined) return contentMetaCache;
  try {
    contentMetaCache = JSON.parse(
      await fs.readFile(CONTENT_META, "utf8")
    ) as ContentMeta;
  } catch {
    contentMetaCache = null;
  }
  return contentMetaCache;
}

/**
 * Estimates reading time for a post based on content length and categories
 */
function estimateReadTime(content: string, categories: string[]): number {
  const wordsPerMinute = 200;
  const wordCount = content.trim().split(/\s+/).length;
  let readTime = wordCount / wordsPerMinute;

  // Math content typically takes longer to read and understand
  if (categories.includes("math")) {
    readTime *= 1.5;
  }

  return Math.max(1, Math.round(readTime));
}

/**
 * Assemble post metadata from raw frontmatter + generated content-meta, applying
  * forgiving defaults so a draft needs only a title: slug from filename, date
  * defaults to today, stage to sighted, excerpt derived from the body, and
 * categories normalized to their canonical labels.
 */
function buildMetadata(
  data: Record<string, unknown>,
  content: string,
  filename: string,
  meta: ContentMeta | null
): PostMetaData {
  const slug = (data.slug as string) || filename.replace(/\.mdx$/, "");
  const categories = (
    Array.isArray(data.categories) ? (data.categories as string[]) : []
  ).map((c) => labelForCategory(c));
  const date =
    (data.date as string) || new Date().toISOString().slice(0, 10);
  const entry = meta?.posts[slug];

  const metadata: PostMetaData = {
    title: (data.title as string) || slug,
    slug,
    excerpt: (data.excerpt as string) || deriveExcerpt(content),
    categories,
    date,
    relatedPosts: Array.isArray(data.relatedPosts)
      ? (data.relatedPosts as string[])
      : [],
    stage: coerceStage(data.stage).stage,
    tended: entry?.tended ?? date,
    backlinks: entry?.backlinks ?? [],
    outgoing: entry?.outgoing ?? [],
    readTime: estimateReadTime(content, categories),
  };

  // Optional fields are OMITTED when absent (not set to undefined): Next's
  // getStaticProps rejects undefined values in serialized props.
  const { confidence } = coerceConfidence(data.confidence);
  if (confidence) metadata.confidence = confidence;
  const mathTooltips = data.mathTooltips as MathTooltipDefinition[] | undefined;
  if (mathTooltips) metadata.mathTooltips = mathTooltips;

  return metadata;
}

/**
 * Parse a single post MDX file and return the post data (with serialized MDX)
 */
const parsePostFile = async (filename: string): Promise<Post> => {
  const filePath = path.join(POSTS_DIR, filename);
  const source = await fs.readFile(filePath, "utf8");
  const { content, data } = matter(source);
  const meta = await loadContentMeta();
  const metadata = buildMetadata(
    data as Record<string, unknown>,
    content,
    filename,
    meta
  );
  const tooltips = metadata.mathTooltips ?? [];

  const mdxSource = await serialize(content, {
    mdxOptions: {
      remarkPlugins: [remarkGfm, remarkMath, [remarkMathTooltips, { tooltips }]],
      rehypePlugins: [
        [
          rehypeKatex,
          {
            throwOnError: false,
            trust: katexTrust,
            strict: katexStrict,
          },
        ],
        [rehypeMathTooltips, { tooltips }],
      ],
    },
  });

  return { ...metadata, content: mdxSource };
};

/**
 * Parse a single post MDX file and return only the metadata
 */
const parsePostMetadataFile = async (
  filename: string
): Promise<PostMetaData> => {
  const filePath = path.join(POSTS_DIR, filename);
  const source = await fs.readFile(filePath, "utf8");
  const { content, data } = matter(source);
  const meta = await loadContentMeta();
  return buildMetadata(
    data as Record<string, unknown>,
    content,
    filename,
    meta
  );
};

/**
 * Sort posts by date descending (newest first)
 */
const sortByDateDesc = <T extends { date: string }>(posts: T[]): T[] =>
  posts.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

/**
 * Load all posts, sorted by date descending
 */
export async function loadPosts(): Promise<Post[]> {
  const postFiles = await fs.readdir(POSTS_DIR);
  const mdxFiles = postFiles.filter((file) => file.endsWith(".mdx"));

  const posts = await Promise.all(mdxFiles.map(parsePostFile));

  return sortByDateDesc(posts);
}

/**
 * Load all posts metadata (no content), sorted by date descending
 */
export async function loadPostsMetadata(): Promise<PostMetaData[]> {
  const postFiles = await fs.readdir(POSTS_DIR);
  const mdxFiles = postFiles.filter((file) => file.endsWith(".mdx"));

  const posts = await Promise.all(mdxFiles.map(parsePostMetadataFile));

  return sortByDateDesc(posts);
}

/**
 * Load a single post by slug
 */
export async function loadPost(slug: string): Promise<Post | null> {
  // First try direct filename match
  const filename = `${slug}.mdx`;
  const filePath = path.join(POSTS_DIR, filename);

  try {
    await fs.access(filePath);
    return parsePostFile(filename);
  } catch {
    // File doesn't exist with that name, search by frontmatter slug
    const postFiles = await fs.readdir(POSTS_DIR);
    const mdxFiles = postFiles.filter((file) => file.endsWith(".mdx"));

    for (const file of mdxFiles) {
      const post = await parsePostFile(file);
      if (post.slug === slug) {
        return post;
      }
    }

    return null;
  }
}
