import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html lang="en" suppressHydrationWarning>
      <Head>
        {/* Preload critical fonts to reduce FOUT/FOIT */}
        <link
          rel="preload"
          href="/fonts/AeionMono-VariableVF.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        <link
          rel="preload"
          href="/fonts/Tickerbit-regular.woff2"
          as="font"
          type="font/woff2"
          crossOrigin="anonymous"
        />
        {/* Syndication feeds (generated by scripts/generate-content-meta.ts) */}
        <link
          rel="alternate"
          type="application/rss+xml"
          title="Elijah's Expedition Log"
          href="/rss.xml"
        />
        <link
          rel="alternate"
          type="application/atom+xml"
          title="Elijah's Expedition Log"
          href="/atom.xml"
        />
      </Head>
      <body className="antialiased">
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
